version: '3.8'

services:
  # -----------------------------------
  # 1. BASES DE DATOS
  # -----------------------------------
  postgres:
    image: postgres:15-alpine
    container_name: ingeniaq-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: ingeniaq_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0
    container_name: ingeniaq-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  # -----------------------------------
  # 2. BACKEND (API)
  # -----------------------------------
  backend:
    build:
      context: ./server   # ðŸ‘ˆ AquÃ­ le decimos: "Busca el Dockerfile en la carpeta server"
      dockerfile: Dockerfile
    container_name: ingeniaq-backend
    restart: always
    ports:
      - "3000:3001"
    depends_on:
      - postgres
      - mongo
    environment:
      PORT: 3001
      CLIENT_URL: http://localhost:8080 # Puerto donde correrÃ¡ tu frontend en Docker
      JWT_SECRET: secreto_super_seguro_ingeniaq_2026
      EMAIL_USER: davinsondiaz264@gmail.com
      EMAIL_PASS: wijjvgvgumgwgrbu
      GEMINI_API_KEY: AIzaSyB1ZrUdJwW5JjZt1IEf5gjAXwx7yxRzxt8
      # ConexiÃ³n interna a los contenedores de DB:
      DATABASE_URL: postgresql://admin:adminpassword@postgres:5432/ingeniaq_db?schema=public
      MONGO_URI: mongodb://admin:adminpassword@mongo:27017/ingeniaq_nosql?authSource=admin

  # -----------------------------------
  # 3. FRONTEND (React + Vite + Nginx)
  # -----------------------------------
  frontend:
    build:
      context: ./client   # ðŸ‘ˆ "Busca el Dockerfile en la carpeta client"
      dockerfile: Dockerfile
    container_name: ingeniaq-frontend
    restart: always
    ports:
      - "8080:80" # AccederÃ¡s en el navegador como http://localhost:8080
    depends_on:
      - backend

volumes:
  pgdata:
  mongodata: