version: '3.8'

services:
  # Base de Datos SQL (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: ingeniaq_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: ingeniaq_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Base de Datos NoSQL (MongoDB)
  mongo:
    image: mongo:6.0
    container_name: ingeniaq_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: